--MEMBER_GRADE
INSERT INTO MEMBER_GRADE(MGRADE, GNO, LOW, HIGH)
    VALUES ('BRONZE', 4, 0, 9);
INSERT INTO MEMBER_GRADE(MGRADE, GNO, LOW, HIGH)
    VALUES ('SILVER', 3 , 10, 19);
INSERT INTO MEMBER_GRADE(MGRADE, GNO, LOW, HIGH)
    VALUES ('GOLD', 2, 20, 29);
INSERT INTO MEMBER_GRADE(MGRADE, GNO, LOW, HIGH)
    VALUES ('DIAMOND', 1, 30, 9999999999);
--MEMBER
INSERT INTO MEMBER(MID, MPW, MNAME, MTEL, MEMAIL, MADDRESS, MBIRTH, MGENDER)
    VALUES ('aaa', '1', '이일일', '010-1111-1111', 'a@aa.com', '서울', '1996-06-06', 'M');
INSERT INTO MEMBER(MID, MPW, MNAME, MTEL, MEMAIL, MADDRESS, MBIRTH, MGENDER)
    VALUES ('bbb', '1', '김길길', '010-2222-2222', 'b@bb.com', '대구', '1995-05-05', 'M');
INSERT INTO MEMBER(MID, MPW, MNAME, MTEL, MEMAIL, MADDRESS, MBIRTH, MGENDER)
    VALUES ('ccc', '1', '소솔솔', '010-3333-3333', 'c@cc.com', '제주', '1994-04-04', 'F');
--CBOARD
INSERT INTO CBOARD(CNO, CID, CTITLE, CCONTENT, CREF, CRE_STEP, CRE_LEVEL)
    VALUES(SEQ_C.NEXTVAL, 'aaa', '문의', '문의요', SEQ_C.CURRVAL, 0, 0);
INSERT INTO CBOARD(CNO, CID, CTITLE, CCONTENT, CREF, CRE_STEP, CRE_LEVEL)
    VALUES(SEQ_C.NEXTVAL, 'aaa', '문의2', '문의요', SEQ_C.CURRVAL, 0, 0);
--GAMES
INSERT INTO GAMES
    VALUES('리니지M');
INSERT INTO GAMES
    VALUES('메이플스토리');
INSERT INTO GAMES
    VALUES('로스트아크'); 
INSERT INTO GAMES
    VALUES('오딘:발할라라이징');
INSERT INTO GAMES
    VALUES('던전앤파이터');
INSERT INTO GAMES
    VALUES('디아블로2:리저렉션');
INSERT INTO GAMES
    VALUES('마비노기');
INSERT INTO GAMES
    VALUES('아이온');
INSERT INTO GAMES
    VALUES('바람의나라:연');
INSERT INTO GAMES
    VALUES('리니지W');
--BOARD
INSERT INTO BOARD (BNO, MID, BBS, GAME, BTITLE, BCOST, BCNAME, BCONTENT, BPHOTO)
    VALUES (SEQ_B.NEXTVAL,'aaa', 'S', '메이플스토리', '템팔아요', 100, '지누러미', '템팔아요', NULL);
INSERT INTO BOARD (BNO, MID, BBS, GAME, BTITLE, BCOST, BCNAME, BCONTENT, BPHOTO)
    VALUES (SEQ_B.NEXTVAL,'bbb', 'B', '마비노기', '템사요', 3000, '지누러미아들', '템살게요', NULL);
--ADMIN
INSERT INTO ADMIN (AID, APW, ANAME)
    VALUES ('ad1', '2', '김관리');
--MESSAGE
INSERT INTO MESSAGE(ENO, SENDID, GETID, ETITLE, ECONTENT)
    VALUES (SEQ_E.NEXTVAL, 'aaa', 'bbb', '살게요', '산다구요');
--TRADE
INSERT INTO TRADE(TNO, BNO, SID, BID)
    VALUES (SEQ_T.NEXTVAL, 1, 'aaa', 'bbb');
SELECT * FROM MEMBER_GRADE;
SELECT * FROM TRADE
COMMIT;